### ISSUE TITLE
[Anglo-Saxons] Elephant Armor Technology?

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/millenniumad#43] opened 2018-10-15 06:55 UTC
I was able to develop elephant armor as part of the technology tree. This is odd and I assume this as a bug.

**Comment by tomasmatys** [comment] 2018-10-15 07:33
@s0600204  should know more, but i believe it is not a bug since most of the technologies  are based on class and template systems

**Comment by s0600204** [comment] 2019-01-22 19:01
(Just noticed this ticket. Clearly I need to look at my notification settings.)

Neither vanilla `0ad` nor the `millenniumad` mod contains a technology for elephant armour.

If you are running multiple community-developed mods at the same time, then - for the time being - you do so at your own risk.

Unless you can prove that this is reproducible with *just* vanilla `0ad` and this mod active (ie. you provide instructions as to how to achieve it), then this is a non-issue with this repository/mod, and as such I am closing it.

**Closed by s0600204** 2019-01-22 19:01 UTC
